### ISSUE TITLE
Ensure jobs are deleted after e2e client

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore-clients#126]
## Long story short
The following should be added to the e2e client tests:

```[tasklist]
### Tasks
- [x] Make sure to stop remaining jobs after tests are done
- [x] Delete jobs after tests are done (in `after_script`)
- [x] Use only clients uploaded to pypi and testpypi
- [x] make sure to pip-freeze to artifacts dir
```
